### ISSUE TITLE
Parsing undefined Error:

### ISSUE THREAD

**Issue by bbuyukcelen** [RebusFoundation/reader-frontend#21]
Steps to reproduce:
1- While logged on through rebus email, upload book: Becoming Myself - Irvin D. Yalom (the book is 20 mb)
2- Receive error: Parsing undefined
TypeError: htmlNavEntry.async is not a function
    at Object.parse (https://rr-dev.rebus.works/components/epub-import-actions.js:46:57)

**Comment by baldurbjarnason** [comment]
Should be fixed in the latest version
