### ISSUE TITLE
*Some* Files Can't Be Downloaded

### ISSUE THREAD

**Issue by bbuyukcelen** [RebusFoundation/reader-frontend#79]
When choosing download from options: read/dowload/delete, bookdownloads get interrupted with message: failed-no file. (But can go and read that same book)
![Screen Shot 2019-06-27 at 11 50 17 AM](https://user-images.githubusercontent.com/42753145/60280852-c27bf080-98d1-11e9-9053-9bc0a8d60063.png)

**Comment by bbuyukcelen** [comment]
It happens with *some* files only, trying to pinpoint which ones and find common denominators.

**Comment by bbuyukcelen** [comment]
After downloading 20some books from my library, I can somewhat safely say the file download gets "interrupted" only for pdf books, with failed-no file error.
epubs are downloading successfully.

**Comment by bbuyukcelen** [comment]
![Screen Shot 2019-06-27 at 12 03 51 PM](https://user-images.githubusercontent.com/42753145/60281813-a7aa7b80-98d3-11e9-9efe-9e429173d124.png)

**Comment by baldurbjarnason** [comment]
Oooh, oooh. It's very helpful to know that it's just PDF files. That means I'm pretty sure I know what's going on there and if I'm correct, it's a trivial fix. Thanks.

**Comment by baldurbjarnason** [comment]
This should be fixed in the next version I deploy (either tomorrow or Tuesday).
